feat : alert component implemented
govardhanreddyc79/Ozone-UI pull request #3
Opened 2022-02-12 19:56 UTC by govardhanreddyc79

alert component done

2022-02-12 20:36 UTC, MaruthiPothuganti requested changes
Suggested a point. Everything else looks good.

2022-02-12 20:36 UTC, MaruthiPothuganti commented on Components/Alert/alert.html
> +            <a class='nav-item' href="https://twitter.com/reddygov16">
good to have a target="_blank" for socials

2022-02-13 04:45 UTC, govardhanreddyc79 commented on Components/Alert/alert.html
> +            <a class='nav-item' href="https://twitter.com/reddygov16">
sure

2022-02-13 05:03 UTC, govardhanreddyc79 commented on Components/Alert/alert.html
> +            <a class='nav-item' href="https://twitter.com/reddygov16">
done

2022-02-13 05:03 UTC, merged